### ISSUE TITLE
automatic releases and luarocks/rocks.nvim support? 

### ISSUE THREAD

**Issue by mrcjkb** [TheSnakeWitcher/hardhat.nvim#1]
Hey :wave:

[rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim) has the ability to install luarocks packages and automatically install dependencies, including tree-sitter parsers.

I was wondering: Would you be open to automating releases and publishing this plugin to luarocks.org?
See also [our wiki page on plugin support](https://github.com/nvim-neorocks/rocks.nvim/wiki/Plugin-support).

I'd be more than happy to help if you have any questions or issues.

**Comment by TheSnakeWitcher** [comment]
Hi, I will do it, it's very cool. Would you recommend me to create a workflow like specified in the docs or to use [nurr](https://github.com/nvim-neorocks/nurr) instead ?

**Comment by mrcjkb** [comment]
Awesome :rocket: 

A workflow file in the plugin repo is the preferred option, because it gives you more flexibility to add/remove dependencies. nurr is just a fallback for people who don't want to publish themseves.

**Comment by TheSnakeWitcher** [comment]
[Done](https://luarocks.org/modules/TheSnakeWitcher/hardhat.nvim) and thanks, any feedback/tips/suggestions are appreciated

**Comment by mrcjkb** [comment]
Awesome, thanks! :rocket: :pray: 

Just one tip: rocks.nvim uses major version bumps to detect potential breaking SemVer changes and warn users before updating.
Of course that's entirely up to you, but we recommend using semver releases (e.g. based on conventional commits) for this reason. A lot of people in the neovim community use 0-ver to communicate that a plugin is not stable, but in practise that won't prevent users from being annoyed by breaking changes.
[Here's a good blog post on the topic if you're interested](https://vhyrro.github.io/posts/versioning/).
